# 데이터 소스 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: scott
    password: 'tiger'

# JPA 설정
  jpa:
    generate-ddl: 'true'
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

# 로그 레벨 설정
logging:
  level:
    org:
      hibernate: info

  # 파일 업로드 설정
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

# 업로드된 파일 저장 위치 설정
upload:
  path: C:/spring/upload